### ISSUE TITLE
TypeError: VSFixSourceMapsPlugin is not a constructor

### ISSUE THREAD

**Issue by acostaf** [joevbruno/vs-fix-sourcemaps#4] opened 2016-06-29 09:44 UTC
@joevbruno 

Getting and error with the plugin **TypeError: VSFixSourceMapsPlugin is not a constructor** I am using version 1.0.1

`       var webpack = require('webpack');
        var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps');

```
    module.exports = {
        entry: './app/main.ts',
        output: {
            path: './dist/',
            filename: 'bundle.js'
        },
        resolve: {
            // Add `.ts` and `.tsx` as a resolvable extension.
            extensions: ['', '.ts', '.js']
        },
        devtool: 'source-map',
        plugins: [
            new VSFixSourceMapsPlugin()
        ]...`
```

**Comment by acostaf** [comment] 2016-06-29 10:34
@joevbruno 

The issue just happens on version 1.0.1, but does not on 0.1.7 the issue with 0.17 is that using Typescript visual studio does not hit the ts file tbut the js file.

**Comment by joevbruno** [comment] 2016-06-29 13:30
Thanks for reporting the issue. While I am not technically supporting Typescript, I will take a look at your issue later today. 1.0 + introduced a significant change in actual VLQ parsing of sourcemaps is now used instead of simply a regex, and actual segments of those sourcemaps, which are not compatible with Visual Studio are removed. I am not sure why you would be getting a TypeError? I would have exacted to get that kind of error myself or in my tests. Is your webpack file a JS file or Typescript file? Also, I am not sure if you are using Babel or how you are resolving your modules, but it is possible that since you are using the 'require' syntax, that you need to do something like  `VSFixSourceMapsPlugin.default` in order to access the primary export of the file - which is a function.

**Comment by acostaf** [comment] 2016-06-29 16:45
I am using a js file, bulding an Angular 2 app with typescript

`   var webpack = require('webpack');
    var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps');
    var path = require('path');

```
module.exports = {
    entry: {
        admin: './app/admin/main.ts',
        tradeReporting: './app/tradeReporting/main.ts'
    },
    output: {
        path: './app/lib',
        filename: '[name]Bundle.js',
        devtoolModuleFilenameTemplate: function (info) {
            var relative = path.relative(__dirname, info.absoluteResourcePath);
            return path.join('/', relative).replace(/\\/g, "/");
        },
        devtoolFallbackModuleFilenameTemplate: function (info) {
            var relative = path.relative(__dirname, info.absoluteResourcePath);
            return path.join('/', relative + info.hash).replace(/\\/g, "/");
        }
    },
    resolve: {
        extensions: ['', '.ts', '.js']
    },
    devtool: 'source-map',
    plugins: [
        new webpack.optimize.UglifyJsPlugin({ exclude: ['adminBundle.js', 'tradeReportingBundle.js'] }),
        new VSFixSourceMapsPlugin()
    ],
    module: {
        loaders: [
          { test: /\.ts/, loader: 'ts-loader', exclude: /node_modules/ },
          { test: /\.html$/, loader: 'raw-loader', exclude: /node_modules/, }
        ]
    },
    watch: true
}`
```

**Comment by joevbruno** [comment] 2016-06-29 16:55
What do you get if you console.log(VSFixSourceMapsPlugin)?

**Comment by acostaf** [comment] 2016-06-29 17:19
@joevbruno 

I am getting this

```
    { default: [Function: VSFixSourceMapsPlugin] }
    C:\LocalFolder\temp\WebApplication10\WebApplication10\webpack.config.js:29
            new VSFixSourceMapsPlugin()
            ^

    TypeError: VSFixSourceMapsPlugin is not a constructor
        at Object.<anonymous> (C:\LocalFolder\temp\WebApplication10\WebApplication10\webpack.config.js:29:9)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:456:32)
        at tryModuleLoad (module.js:415:12)
        at Function.Module._load (module.js:407:3)
        at Module.require (module.js:466:17)
        at require (internal/module.js:20:19)
        at module.exports (C:\LocalFolder\temp\WebApplication10\WebApplication10\node_modules\webpack\bin\convert-argv.js:80:13)
        at Object.<anonymous> (C:\LocalFolder\temp\WebApplication10\WebApplication10\node_modules\webpack\bin\webpack.js:39:40)
```

**Comment by joevbruno** [comment] 2016-06-29 17:20
Ok. That is what I suspected @acostaf.

Try this: 

``` js
var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps').default; // add .default

...
  plugins: [
        new webpack.optimize.UglifyJsPlugin({ exclude: ['adminBundle.js', 'tradeReportingBundle.js'] }),
        new VSFixSourceMapsPlugin() // stays the same
    ],
```

**Comment by acostaf** [comment] 2016-06-29 17:44
@joevbruno that worked thanks. 

Do we need to do the devtoolModuleFilenameTemplate, devtoolFallbackModuleFilenameTemplate and run the UglifyJsPlugin with the latest version ?

**Comment by joevbruno** [comment] 2016-06-29 17:47
You do need to do have devtoolModuleFilenameTemplate and devtoolFallbackModuleFilenameTemplate or you won't see any source code when VS pauses on break points. You do not need uglify js unless you want to minify production code with it =)

**Closed as completed** 2016-06-29 17:48 UTC

**Comment by acostaf** [comment] 2016-06-29 19:22
@joevbruno I noticed that loading the maps it is also loading ALL THE MAPPING including libraries killing my Visual studio, 

Any idea how to exclude libs from your maps?

**Comment by joevbruno** [comment] 2016-06-29 19:36
@acostaf this is the intended behavior. What you could do is create a separate bundle file of all your vendors, which does not include the plugin (checkout webpack's library options under the output options), and another bundle of just your code which does use this plugin. That may solve the issue.

**Comment by acostaf** [comment] 2016-06-30 11:54
@joevbruno Done it but not much luck.

I have split my entry

```
entry: {
    polyfills: './app/lib/polyfill.ts',
    admin: './app/admin/main.ts',
    tradeReporting: './app/tradeReporting/main.ts',
    vendor: './app/lib/vendor.ts'
},
```

and 

```
    new webpack.optimize.CommonsChunkPlugin({ name: ['admin', 'tradeReporting', 'vendor', 'polyfills'] }, Infinity),
```

Deleted by devtool and star using SourceMapDevToolPlugin in order to create my maps for desired files
        new webpack.SourceMapDevToolPlugin({ filename: '[file].map', include: ['adminBundle.js', 'tradeReportingBundle.js'] }),

Everything look awasone but cannot get visual studio tp hit the break point on the ts files, normally will break on the js file, Any idea what I could be missing?

**Comment by acostaf** [comment] 2016-06-30 15:28
@joevbruno I fixed it.

I am using SourceMapDevToolPlugin instead "devtool: 'source-map'" and "moduleFilenameTemplate: '../.[resourcePath]" instead of 

```
    devtoolModuleFilenameTemplate: function (info) {
        var relative = path.relative(__dirname, info.absoluteResourcePath);
        return path.join('/', relative + info.hash).replace(/\\/g, "/");
    },
    devtoolFallbackModuleFilenameTemplate: function (info) {
        var relative = path.relative(__dirname, info.absoluteResourcePath);
        return path.join('/', relative + info.hash).replace(/\\/g, "/");
    }
```

so my config know looks like that: 

```
    var webpack = require('webpack');
    var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps').default;
    var path = require('path');

    module.exports = {
        entry: {
            polyfills: './app/lib/polyfill.ts',
            admin: './app/admin/main.ts',
            tradeReporting: './app/tradeReporting/main.ts',
            vendor: './app/lib/vendor.ts'
        },
        output: { path: './app/lib', filename: '[name]Bundle.js' },
        resolve: { extensions: ['', '.ts', '.js'] },
        plugins: [
             new webpack.optimize.CommonsChunkPlugin({ name: ['admin', 'tradeReporting', 'vendor', 'polyfills'] }, Infinity),
             new webpack.optimize.DedupePlugin(),
             new webpack.optimize.OccurrenceOrderPlugin(),
             new webpack.SourceMapDevToolPlugin({
                 filename: '[file].map', include: ['adminBundle.js', 'tradeReportingBundle.js'],
                 moduleFilenameTemplate: '../.[resourcePath]'
             }),
             new VSFixSourceMapsPlugin()
        ],
        module: {
            loaders: [
              { test: /\.ts/, loader: 'ts-loader', exclude: /node_modules/ },
              { test: /\.html$/, loader: 'raw-loader', exclude: /node_modules/, }
            ]
        },
        watch: true
    };
```

so the key is to add this moduleFilenameTemplate: '../.[resourcePath]' which replaces "webpack:///"

**Comment by joevbruno** [comment] 2016-07-01 19:13
@acostaf glad you worked it out! best of luck on your angular project. 👍
